import sqlite3
import pandas as pd
import streamlit as st
import database as db

db.init_db()

st.set_page_config(page_title="Admin Control Center", layout="wide", page_icon="🔒")

def load_css(file_name="style.css"):
    try:
        with open(file_name) as f:
            st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
    except FileNotFoundError:
        pass

load_css("style.css")

# --- SESSION STATE & RESTORE LOGIN VIA URL ---
if "admin_logged_in" not in st.session_state:
    st.session_state.admin_logged_in = False

if not st.session_state.admin_logged_in and st.query_params.get("adm") == "true":
    st.session_state.admin_logged_in = True


# ==========================================
# 1. HALAMAN LOGIN ADMIN (BELUM AUTHENTICATE)
# ==========================================
if not st.session_state.admin_logged_in:
    st.markdown("<br><h2 style='text-align: center;'>🔒 Admin Control Center</h2>", unsafe_allow_html=True)
    st.markdown("<p style='text-align: center; color: #64748B;'>Internal System Owner Access Only</p><br>", unsafe_allow_html=True)

    col1, col2, col3 = st.columns([1, 1.5, 1])
    with col2:
        username_admin = st.text_input("Admin Username", key="adm_user")
        password_admin = st.text_input("Admin Password", type="password", key="adm_pass")
        st.write("")
        if st.button("Authenticate", type="primary", use_container_width=True):
            user_data = db.login_user(username_admin.strip(), password_admin.strip())
            if user_data and len(user_data) >= 3 and user_data[2] == "admin":
                st.session_state.admin_logged_in = True
                st.query_params["adm"] = "true"
                st.success("Autentikasi Admin Berhasil!")
                st.rerun()
            else:
                st.error("Akses Ditolak: Kredensial atau hak akses salah.")


# ==========================================
# 2. DASHBOARD ANALYTICS ADMIN (SETELAH LOGIN)
# ==========================================
else:
    with st.sidebar:
        st.markdown("### 🔒 **Admin Console**")
        st.caption("System Operational Control")
        st.markdown("---")
        
        # Form Tambah Admin Baru
        with st.expander("👤 Tambah Admin Baru", expanded=False):
            new_adm_user = st.text_input("Username Admin Baru", key="new_adm_u")
            new_adm_pass = st.text_input("Password Admin Baru", type="password", key="new_adm_p")
            if st.button("Buat Admin", use_container_width=True):
                if new_adm_user and new_adm_pass:
                    conn = sqlite3.connect(db.DB_NAME)
                    cursor = conn.cursor()
                    try:
                        cursor.execute(
                            "INSERT INTO users (username, password, role, api_key) VALUES (?, ?, 'admin', '')",
                            (new_adm_user.strip(), new_adm_pass.strip())
                        )
                        conn.commit()
                        st.success(f"Admin '{new_adm_user}' berhasil dibuat!")
                    except sqlite3.IntegrityError:
                        st.error("Username sudah terpakai.")
                    finally:
                        conn.close()
                else:
                    st.warning("Isi semua bidang input.")

        st.markdown("<br>", unsafe_allow_html=True)
        if st.button("🚪 Logout Admin", use_container_width=True):
            st.session_state.admin_logged_in = False
            st.query_params.clear()
            st.rerun()

    st.markdown("## 📊 System Performance & Analytics")
    st.markdown("---")

    # --- METRIK ANALITIK UTAMA ---
    total_users, total_srs, avg_chars = db.get_advanced_admin_metrics()

    col1, col2, col3 = st.columns(3)
    col1.metric("👥 Total Registered Users", total_users)
    col2.metric("📄 Total SRS Generated", total_srs)
    col3.metric("📊 Avg. Document Length", f"{avg_chars:,} Chars")

    st.markdown("---")

    # --- TABEL LOG AKTIVITAS SYSTEM ---
    st.markdown("### 📜 System Usage Logs")
    conn = sqlite3.connect(db.DB_NAME)
    df_logs = pd.read_sql_query('''
        SELECT 
            s.id AS "SRS ID",
            u.username AS "Generated By",
            s.judul AS "Project Title",
            LENGTH(s.hasil_srs) AS "Doc Size (Chars)",
            s.created_at AS "Timestamp"
        FROM srs_history s
        JOIN users u ON s.user_id = u.id
        ORDER BY s.created_at DESC
    ''', conn)
    conn.close()

    if not df_logs.empty:
        st.dataframe(df_logs, use_container_width=True)
    else:
        st.info("Belum ada data aktivitas dokumen.")